// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuX2nztkOdQiDBTH6JyH8HjEorqW9O-nw',
    appId: '1:493063237095:web:78045d0845a4a0688b2142',
    messagingSenderId: '493063237095',
    projectId: 'final-mobile-fb4a0',
    authDomain: 'final-mobile-fb4a0.firebaseapp.com',
    databaseURL: 'https://final-mobile-fb4a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-mobile-fb4a0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANdSXC7DydkDyPdhbHTuYLRDg0d6-bbEY',
    appId: '1:493063237095:android:d166037ac863aff78b2142',
    messagingSenderId: '493063237095',
    projectId: 'final-mobile-fb4a0',
    databaseURL: 'https://final-mobile-fb4a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-mobile-fb4a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATQV-_Vi3F_wIaYRjChVdJrg30HpP9y7c',
    appId: '1:493063237095:ios:41309d4c68f2680b8b2142',
    messagingSenderId: '493063237095',
    projectId: 'final-mobile-fb4a0',
    databaseURL: 'https://final-mobile-fb4a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-mobile-fb4a0.appspot.com',
    androidClientId: '493063237095-mkim0qgo2kqumdlnf4o0h89f7sl1hpjm.apps.googleusercontent.com',
    iosClientId: '493063237095-p57cjv7muogju7mplg518n31pufhjurg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiligrim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATQV-_Vi3F_wIaYRjChVdJrg30HpP9y7c',
    appId: '1:493063237095:ios:41309d4c68f2680b8b2142',
    messagingSenderId: '493063237095',
    projectId: 'final-mobile-fb4a0',
    databaseURL: 'https://final-mobile-fb4a0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-mobile-fb4a0.appspot.com',
    androidClientId: '493063237095-mkim0qgo2kqumdlnf4o0h89f7sl1hpjm.apps.googleusercontent.com',
    iosClientId: '493063237095-p57cjv7muogju7mplg518n31pufhjurg.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiligrim',
  );
}
